device: cuda
model_config: model/ViT-B-16.json
model_ckpt: model/tsbir_model_final.pt
is_train: False
retrieval_metric: cosine  # cosine | dot
top_k: 5

encoding:
  batch_size: 32
  num_workers: 0
  image_dir: images/

inference:
  sketch_path: sketches/COCO_val2014_000000163852.jpg
  caption: "a plate of food with a fork and knife"
  save_result_path: retrieval_result.jpg